### ISSUE TITLE
Slightly more info on Hashed Info and ISRC in the CSV-file

### ISSUE THREAD

**Issue by kragil** [andygruber/songseeker-card-generator#5]
Hello, great project! Thank you very much!

I just wanted to add my own songs and fix a few broken ones, but I don't know how to compute the "Hashed Info" field and where to get is ISRC thing. Can you give me a hint?
I just need a tiny bit of info, and then I am golden. 
Pretty please ;-)

THanks again!

**Comment by andygruber** [comment]
Thank you very much for the feedback.

This repo is just for generating your own cards, hashed Info and ISRC is not required here.

As for the other repo in https://github.com/andygruber/songseeker-hitster-playlists . As far as I remember, I got the ISRC when I exported the playlist from directly from Spotify. As I understand that value, it will never change and is a uniqe identifier of a Song from a certain artist.

There also is [verifyYoutubeLinks.py](https://github.com/andygruber/songseeker-hitster-playlists/blob/main/verifyYoutubeLinks.py) which can be used to generate and verify the value for "Hashed Info". The idea is to get to know if links are broken are something has changed. In reality its not 100% proof that the links still work, but its a first step.

Both values (hashed info and ISRC) are not used in the game at this point in time.

Help in fixing broken links is much appreciated.

If you really want to print your own cards I may have an interesting update (bigger cards, colored front instead of white, just overall more nice looking) upcoming.
